# Generated by Django 4.2.27 on 2026-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_approved_user_phone_number_user_shop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('RETAILER', 'Retailer'), ('NURSERY', 'Nursery/Plantation')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
