# Generated by Django 4.2.27 on 2026-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_business_type_user_gst_number_user_shop_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identity Proof (AADHAR/PAN)'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
