# Generated by Django 4.2.27 on 2026-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='care_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(choices=[('Slow', 'Slow'), ('Medium', 'Medium'), ('Fast', 'Fast')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ideal_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maintenance_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pet_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sunlight',
            field=models.CharField(choices=[('Full Sun', 'Full Sun'), ('Bridge Light', 'Bright Indirect Light'), ('Partial Shade', 'Partial Shade'), ('Low Light', 'Low Light')], default='Bright Indirect Light', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='watering',
            field=models.CharField(choices=[('Frequent', 'Frequent (3-4 times/week)'), ('Moderate', 'Moderate (1-2 times/week)'), ('Occasional', 'Occasional (Every 2 weeks)'), ('Very Low', 'Very Low (Monthly)')], default='Moderate', max_length=100),
        ),
    ]
