# Generated by Django 4.2.27 on 2026-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_benefits_product_care_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='environment',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('BOTH', 'Both (Indoor & Outdoor)')], default='INDOOR', max_length=20),
        ),
    ]
